apiVersion: skaffold/v3
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: hello-anthos
    context: src
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
deploy:
  kubectl: {}
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {
      projectId: anthos-multi-project
    }