apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: hello-anthos
    context: src
deploy:
  kubectl:
    manifests:
      - k8s/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {
      projectId: anthos-multi-project
    }